version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: base
    stdin_open: true
    tty: true
    env_file: ./app/.env
    volumes:
      - code-sync:/app:delegated
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  chain:
    build:
      context: ./chain
      dockerfile: Dockerfile
      target: base
    stdin_open: true
    tty: true
    ports:
      - "8545:8545"
    volumes:
      - ./chain:/chain

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tickex
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  code-sync: 

x-mutagen:
  sync:
    app-code: 
      alpha: "./app" 
      beta: "volume://code-sync"
      mode: "two-way-resolved"
      ignore:
        vcs: true
